#!/usr/bin/env php
<?php
/*
$pwu_data = posix_getpwuid(posix_geteuid());
$username = $pwu_data['name'];

if($username !== 'nginx'){
	echo 'Console MUST be executed as "nginx" user - current user : '.$username.PHP_EOL;
	exit(1);
}*/
require_once(__DIR__.'/autoload.php');

use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Debug\Debug;

// if you don't want to setup permissions the proper way, just uncomment the following PHP line
// read http://symfony.com/doc/current/book/installation.html#configuration-and-setup for more information
umask(0000);

set_time_limit(0);


$input = new Symfony\Component\Console\Input\ArgvInput();
$env = $input->getParameterOption(array('--env', '-e'), getenv('SERVER_ENVIRONMENT') ?: 'dev');
$debug = getenv('SYMFONY_DEBUG') !== '0' && !$input->hasParameterOption(array('--no-debug', '')) && $env !== 'prod';

if ($debug) {
    Debug::enable();
}

$kernel = new AppKernel($env, $debug);
$application = new Application($kernel);
$application->run($input);